// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDkTJGRw6DAm9VWoAayfhtqgyGqnYnbNyk',
    appId: '1:749157335748:web:e33f338090fee39a10bf91',
    messagingSenderId: '749157335748',
    projectId: 'movieapp-1c527',
    authDomain: 'movieapp-1c527.firebaseapp.com',
    storageBucket: 'movieapp-1c527.firebasestorage.app',
    measurementId: 'G-RP6PM0Y4PE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDS7F_IB7rw6YQ2I8r8zTS-14lXzDcSkvk',
    appId: '1:749157335748:android:74f8fddbdde403b910bf91',
    messagingSenderId: '749157335748',
    projectId: 'movieapp-1c527',
    storageBucket: 'movieapp-1c527.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDUhcz2Gk12eoKQm1vWCa_kc3BqLAMx35U',
    appId: '1:749157335748:ios:1f7f1ebc5e7888f210bf91',
    messagingSenderId: '749157335748',
    projectId: 'movieapp-1c527',
    storageBucket: 'movieapp-1c527.firebasestorage.app',
    iosBundleId: 'com.example.movieapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDUhcz2Gk12eoKQm1vWCa_kc3BqLAMx35U',
    appId: '1:749157335748:ios:1f7f1ebc5e7888f210bf91',
    messagingSenderId: '749157335748',
    projectId: 'movieapp-1c527',
    storageBucket: 'movieapp-1c527.firebasestorage.app',
    iosBundleId: 'com.example.movieapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDkTJGRw6DAm9VWoAayfhtqgyGqnYnbNyk',
    appId: '1:749157335748:web:5db86aee1d12f94a10bf91',
    messagingSenderId: '749157335748',
    projectId: 'movieapp-1c527',
    authDomain: 'movieapp-1c527.firebaseapp.com',
    storageBucket: 'movieapp-1c527.firebasestorage.app',
    measurementId: 'G-KKEM21JX5F',
  );
}
